name: Waka Readme

on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "False"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
